version: "2.2"

services:
  namenode:
    build: ./namenode
    hostname: namenode
    cpus: 0.25
    mem_limit: 500m
    mem_reservation: 500m
    container_name: namenode
    volumes:
      - ./data/namenode:/hdfsdata
    environment:
      - CLUSTER_NAME=test
    ports:
      - "50070:50070"

  resourcemanager:
    build: ./resourcemanager
    hostname: resourcemanager
    cpus: 0.25
    mem_limit: 500m
    mem_reservation: 500m
    container_name: resourcemanager
    depends_on:
      - "namenode"
    links:
      - "namenode"
    ports:
      - "58088:8088"

  datanode1:
    build: ./datanode
    hostname: datanode1
    container_name: datanode1
    cpus: 0.5
    mem_limit: 500m
    mem_reservation: 500m
    depends_on:
      - "namenode"
    links:
      - "namenode"
    volumes:
      - ./data/datanode1:/hdfsdata

  datanode2:
    build: ./datanode
    hostname: datanode2
    cpus: 0.5
    mem_limit: 500m
    mem_reservation: 500m
    container_name: datanode2
    depends_on:
      - "namenode"
    links:
      - "namenode"
    volumes:
      - ./data/datanode2:/hdfsdata

  datanode3:
    build: ./datanode
    hostname: datanode3
    cpus: 0.5
    mem_limit: 500m
    mem_reservation: 500m
    container_name: datanode3
    depends_on:
      - "namenode"
    links:
      - "namenode"
    volumes:
      - ./data/datanode3:/hdfsdata
     
  nodemanager1:
    build: ./nodemanager
    hostname: nodemanager1
    cpus: 1.0
    mem_limit: 4g
    mem_reservation: 4g
    depends_on:
      - "resourcemanager"
    links:
      - "resourcemanager"

  nodemanager2:
    build: ./nodemanager
    hostname: nodemanager2
    container_name: nodemanager2
    cpus: 1.0
    mem_limit: 4g
    mem_reservation: 4g
    depends_on:
      - "resourcemanager"
    links:
      - "resourcemanager"

  nodemanager3:
    build: ./nodemanager
    hostname: nodemanager3
    container_name: nodemanager3
    cpus: 1.0
    mem_limit: 4g
    mem_reservation: 4g
    depends_on:
      - "resourcemanager"
    links:
      - "resourcemanager"
